### PR TITLE
Some spelling ideas

### PR DESCRIPTION
**Pull request by CWWhitney**
Best to get Eike involved here. He may want to integrate these into the main package?

### CODE REVIEW

**Comment by CWWhitney** [comment]
The bots seem to approve. 

Cory





On Apr 6, 2019, at 8:58 AM, codecov[bot] <notifications@github.com> wrote:

Codecov Report

Merging #2 into master will not change coverage.
The diff coverage is n/a.


@@         Coverage Diff          @@
##           master    #2   +/-   ##

====================================
  Coverage       0%    0%           
====================================
  Files           3     3           
  Lines         126   126           
====================================
  Misses        126   126

Continue to review full report at Codecov.

Legend - Click here to learn more
Δ = absolute <relative> (impact), ø = not affected, ? = missing data
Powered by Codecov. Last update 56a59db...1a46005. Read the comment docs.

**Comment by CWWhitney** [comment]
I was wrong about the size of data that can be uploaded by the way. We should use another repository system. Maybe figshare or Arxiv for longe term storage and maybe Dropbox in the meantime?

Cory

**Comment by Issoufou-Liman** [comment]
I am merging the spelling ideas you proposed.

> 
> I was wrong about the size of data that can be uploaded by the way. We should use another repository system. Maybe figshare or Arxiv for longe term storage and maybe Dropbox in the meantime? Cory
> […](#)
> On 6 Apr 2019, at 09:02, Cory Whitney ***@***.***> wrote: The bots seem to approve. Cory On Apr 6, 2019, at 8:58 AM, codecov[bot] ***@***.***> wrote: Codecov Report Merging #2 into master will not change coverage. The diff coverage is n/a. @@ Coverage Diff @@ ## master #2 +/- ## ==================================== Coverage 0% 0% ==================================== Files 3 3 Lines 126 126 ==================================== Misses 126 126 Continue to review full report at Codecov. Legend - Click here to learn more Δ = absolute <relative> (impact), ø = not affected, ? = missing data Powered by Codecov. Last update [56a59db...1a46005](https://github.com/Issoufou-Liman/decisionSupportExtra/compare/56a59db...1a46005). Read the comment docs. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

I will have a look at figshare and Arxiv, but It may take some times.

**Comment by Issoufou-Liman** [comment]
For Eike I sent you the invitation at the same time, but I will notify him via Email.

**Pull request merged**
